CREATE DATABASE SENAI_SP_MEDICAL_GROUP;

CREATE TABLE CLINICA(
      ID INT IDENTITY PRIMARY KEY 
	  ,NOME VARCHAR(250) NOT NULL
	  ,ENDERECO VARCHAR(250) NOT NULL UNIQUE
	  ,HORARIO_DE_ATENDIMENTO VARCHAR(250) NOT NULL
	  ,CNPJ CHAR (18) NOT NULL UNIQUE
	  ,RAZAO_SOCIAL VARCHAR (250) NOT NULL UNIQUE
);

CREATE TABLE ESPESIALIDADES(
      ID INT IDENTITY PRIMARY KEY 
	  ,EPESIALIDADE VARCHAR(250) NOT NULL 
);

CREATE TABLE TIPOS_USUARIOS (
      ID INT IDENTITY PRIMARY KEY
	  ,TIPO VARCHAR(250) NOT NULL
);

CREATE TABLE USUARIOS (
      ID INT IDENTITY PRIMARY KEY
	  ,NOME VARCHAR (250) NOT NULL
	  ,EMAIL VARCHAR (250) NOT NULL unique
	  ,SENHA VARCHAR (250) NOT NULL 
	  ,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIOS(ID)
);

CREATE TABLE PRONTUARIOS(
      ID INT IDENTITY PRIMARY KEY 
	  ,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
	  ,DATA_NACIMENTO DATE NOT NULL
	  ,TELEFONE VARCHAR (20) NOT NULL
	  ,RG VARCHAR (20) NOT NULL UNIQUE
	  ,CPF VARCHAR (20) NOT NULL UNIQUE
	  ,ENDERECO VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE STATUS_CONSULTA (
      ID INT IDENTITY PRIMARY KEY 
	  ,TIPO_CONSULTA VARCHAR (250) NOT NULL UNIQUE
);

CREATE TABLE MEDICO (
      ID INT IDENTITY PRIMARY KEY 
	  ,NOME VARCHAR (250) NOT NULL
	  ,CRM CHAR (5) NOT NULL UNIQUE
	  ,RAZAO_SOCIAL VARCHAR(250) NOT NULL
	  ,ENDERECO VARCHAR (250) NOT NULL
	  ,ID_ESPESIALIDADE INT FOREIGN KEY REFERENCES ESPESIALIDADES(ID)
	  ,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID)
	  ,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) UNIQUE
);

CREATE TABLE CONSULTA (
      ID INT IDENTITY PRIMARY KEY 
	  ,DESCRICAO VARCHAR (250)
	  ,ID_MEDICO INT FOREIGN KEY REFERENCES MEDICO(ID)
	  ,ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIOS(ID)
	  ,DATA_AGENDAMENTO DATETIME NOT NULL
	  ,ID_STATUS INT FOREIGN KEY REFERENCES STATUS_CONSULTA(ID) 
);
----------------------------------------------------------------------------------------------

SELECT * FROM ESPESIALIDADES

SELECT * FROM STATUS_CONSULTA

SELECT * FROM CONSULTA

SELECT * FROM PRONTUARIOS

SELECT * FROM MEDICO

SELECT * FROM CLINICA

SELECT * FROM USUARIOS

SELECT * FROM TIPOS_USUARIOS

SELECT * FROM PRONTUARIOS INNER JOIN CONSULTA ON PRONTUARIOS.ID = CONSULTA.ID_PRONTUARIO

SELECT * FROM PRONTUARIOS INNER JOIN CONSULTA ON PRONTUARIOS.ID = CONSULTA.ID_PRONTUARIO INNER JOIN MEDICO ON PRONTUARIOS.ID = CONSULTA.ID_MEDICO

SELECT * FROM MEDICO INNER JOIN ESPESIALIDADES ON ESPESIALIDADES.ID = MEDICO.ID_ESPESIALIDADE

SELECT * FROM MEDICO INNER JOIN CLINICA ON CLINICA.ID = MEDICO.ID_CLINICA

SELECT CONVERT (VARCHAR (10) , DATA_NACIMENTO , 103 ) FROM PRONTUARIOS

SELECT COUNT (*) FROM USUARIOS

CREATE PROCEDURE spMOSTRA_ESPECIALIDADE_DO_MEDICO
AS
SELECT COUNT (*) FROM MEDICO WHERE ID_ESPESIALIDADE = '3'
EXEC spMOSTRA_ESPECIALIDADE_DO_MEDICO

CREATE PROCEDURE spMOSTRAR_IDADE_PACIENTE
AS
SELECT FLOOR (DATEDIFF(DAY, DATA_NACIMENTO, GETDATE()) /365.25) AS IDADE FROM PRONTUARIOS
EXEC spMOSTRAR_IDADE_PACIENTE
----------------------------------------------------------------------------------------------
INSERT INTO CLINICA
VALUES ('Clinica Possarles','Av. Barão Limeira, 532, São Paulo, SP','07:00 a 19:00','86.400.902/0001-30','SP Medical Group')
----------------------------------------------------------------------------------------------
DBCC CHECKIDENT ('[MEDICO]', RESEED, 41);

--------------------------------------------------------------------------------------------
delete from CONSULTA  WHERE ID > 41  